name: Expo
on:
  - push
jobs:
  publish:
    # if: github.ref == 'master'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Expo Publish
        uses: ./.github/actions/expo
        with:
          entrypoint: /publish.sh
        env:
          EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
  build:
    # if: github.ref == 'master'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Turtle Build
        uses: ./.github/actions/expo
        with:
          entrypoint: /entrypoint.sh
        env:
          TURTLE_VERSION: 0.13.6
          PLATFORM: android
          EXPO_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
  # build:
  #   name: build
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ./.github/actions/expo
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: ./.github/actions/expo
  #       working-directory: ./app
  #       env:
  #         TURTLE_VERSION: 0.13.6
  #         PLATFORM: android
  #       run: |
  #         cat app.json | jq '.expo.sdkVersion' -r > /tmp/expo-sdk-version
  #         yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
  #         turtle setup:$PLATFORM --sdk-version `cat /tmp/expo-sdk-version`
