name: Expo
on:
  - push
jobs:
  publish:
    if: github.ref == 'master'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Expo
        uses: ./.github/actions/pulumi
        with:
          entrypoint: /appEntrypoint.sh
        env:
          EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}