name: Expo
on:
  - push
jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Expo Publish
        uses: ./.github/actions/expo
        with:
          entrypoint: /publish.sh
        env:
          EXPO_CLI_USERNAME: timmyers
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
          SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
  build:
    if: github.ref == 'refs/heads/master'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Turtle Build
        uses: ./.github/actions/expo
        with:
          entrypoint: /build.sh
        env:
          TURTLE_VERSION: 0.13.10
          PLATFORM: android
          EXPO_USERNAME: timmyers
          EXPO_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: android
          path: app/brewed-here.aab
