name: Expo
on:
  - push
jobs:
  publish:
    if: github.ref == 'master'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Expo
        uses: ./.github/actions/expo
        with:
          entrypoint: /entrypoint.sh
        env:
          EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: docker://dsokal/expo-turtle-android
      env:
        TURTLE_VERSION: 0.13.6
        PLATFORM: android
    steps:
      - uses: actions/checkout@v1
      - name: Determine Expo SDK version for this project
        working-directory: ./app
        run: cat app.json | jq '.expo.sdkVersion' -r > /tmp/expo-sdk-version
