name: Release
on:
  - push
jobs:
  release:
    # needs: publish
    if: github.ref == 'refs/heads/master'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Release
        uses: timmyers/brewed-here-expo:sdk36
        # uses: ./.github/actions/expo
        with:
          entrypoint: /build-entrypoint.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
          ANDROID_MAPS_API_KEYS: ${{ secrets.ANDROID_MAPS_API_KEYS }}
          TURTLE_VERSION: 0.13.10
          PLATFORM: android
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: env.TURTLE_BUILD == true
        with:
          name: brewed-here.aab
          path: app/brewed-here.aab
